error_codes = {
    "display": {
        0: "Lost communication between master and slave",
        1: "Meter lost communication warning",
        2: "HMI EEPROM error",
        3: "HMI RTC error",
        4: "BMS device error",
        5: "BMS lost communication warning",
        11: "RVoltHighFault",
        12: "RVoltLowFault",
        13: "SVoltHighFault",
        14: "SVoltLowFault",
        15: "TVoltHighFault",
        16: "TVoltLowFault",
        17: "FreqHighFault",
        18: "FreqLowFault",
        23: "NoGridFault",
        24: "PVInputModeFault",
        25: "HWPVCurrHighFault",
        26: "PVVolHighFault",
        27: "HWBusVoltageHighFault",
    },
    "master_1": {
        0: "Master Bus Voltage High",
        1: "Master Bus Voltage Low",
        2: "Master Grid Phase Error",
        3: "Master PV Voltage High Error",
        4: "Master Islanding Error",
        5: "Reserved",
        6: "Master PIN input Error",
        7: "Communication between DSP and FPGA",
        8: "Master HV Bus Voltage High",
        9: "Master PV Current High",
        10: "Master HV IW Current High",
        14: "Master Grid NV Voltage Too High",
        15: "Master DRM0 Error",
        16: "Master Fan1 Error",
        17: "Master Fan2 Error",
        18: "Master Arc Error",
        19: "Master Arc Error",
        20: "Master SPV W Current High",
        21: "Master Battery Voltage High",
        22: "Master Battery Charge Voltage High",
        23: "Master Battery Charge OverTime",
        24: "Master Battery SoftConnect Timed",
        25: "Master Battery OverLoad",
        26: "Master Output OverLoad",
        27: "Master Battery Open Circuit Error",
        29: "Battery Discharge Voltage Low",
        30: "Authority expires",
        31: "Lost Communication D->C",
    },
    "master_2": {
        0: "Master Relay Error",
        1: "Master EEPROM Error",
        2: "Master Temperature High Error",
        3: "Master Temperature Low Error",
        4: "Lost Communication M<->S",
        5: "Master DCI Device Error",
        6: "Master DCI Device Error",
        7: "Master Current Sensor Error",
        8: "Master PV Voltage High",
        9: "Master PV Voltage Low",
        10: "Master Grid Frequency High",
        11: "Master Grid Frequency Low",
        12: "Reserved (bit 52)",
        13: "Reserved (bit 53)",
        14: "Master Phase1 DCV Error",
        15: "Master Phase2 DCV Error",
        16: "Master Grid Error",
        17: "Master Grid Error",
        18: "Reserved (bit 56)",
        19: "Reserved (bit 57)",
        20: "Master Grid Error",
        21: "Master Phase1 DCV Error",
        22: "Master Phase2 DCV Error",
        23: "Master Phase3 DCV Error",
        30: "Master E50 error",
        31: "Master Bus Voltage Balance Error",
    }
}
